version: "3.7"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongo