# Generated by Django 2.2.6 on 2019-10-20 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('cpf', models.IntegerField()),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=45)),
                ('cidade', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('cpf', models.IntegerField()),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=45)),
                ('cidade', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Curso')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
